# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" "sr_mod" "rtsx_pci_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/8f497f19-8ee0-4417-b667-0e705dd0570b";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8C48-0D92";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  networking.hostName = "xcd"; # Define your hostname.
  networking.networkmanager.enable = true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  ## Adding Nvidia configurations for steam.
  # hardware.opengl has beed changed to hardware.graphics
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };
  # Enables nvidia for both xserver and wayland
  services.xserver.videoDrivers = ["nvidia"];
  # enables some options that are recommended and other that helped resolve sleep issue.
  # Prime disabled since my system is detecting one GPU using nix shell nixpkgs#pciutils -c lspci | grep ' VGA '
  hardware.nvidia = {
    #use nvidia-smi to see status of GPU
    modesetting.enable = true;
    powerManagement.enable = true; #this partially fixed waking from sleep issue.
    open = false;
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
    #prime = {
    #  sync = {
    #    enable = false;
    #  };
    #};
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
